---
sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.cache/pip
node_js:
  - '4.3.2'

before_install:
  - npm install -g yarn serverless
install:
  - yarn install

script:
  # TODO
  - echo "do some tests..."

before_deploy:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # install aws cli
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - aws --version
  # account number
  - account_number=$(aws sts get-caller-identity --output text --query 'Account')
deploy:
  - provider: script
    script: ./scripts/deploy.sh | sed -e "s/${account_number}/SECRET/g"
    skip_cleanup: true
    on:
      branch: deploy/*
