---
sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.cache/pip
node_js:
  - '4.3.2'

before_install:
  - npm install -g serverless
install:
  - yarn install

script:
  # TODO
  - echo "do some tests..."

before_deploy:
  # install aws cli
  - sudo apt-get -y install python-pip
  - pip install awscli
  - aws --version
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # prune to reduce package size
  - npm prune --production
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
