service: micropost

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ecr:DescribeImages"
        - "ecr:BatchDeleteImage"
      Resource: "*"

functions:
  notifyToSlack:
    handler: functions/notify_to_slack.handle
    events:
      - sns: web_autoscaled
  cleanEcrImages:
    handler: functions/clean_ecr_images.handle
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: true
          input:
            age: 2
            repositoryName: 'micropost/frontend'
      - schedule:
          rate: rate(24 hours)
          enabled: true
          input:
            age: 2
            repositoryName: 'micropost/backend'

custom:
  defaultStage: stg
  writeEnvVars:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

plugins:
  - serverless-plugin-write-env-vars
