service: micropost

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  notifyToSlack:
    handler: functions/notify_to_slack.handle
    events:
      - sns: web_autoscaled

custom:
  defaultStage: stg
  writeEnvVars:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

plugins:
  - serverless-plugin-write-env-vars
